spring:
  application:
    name: StockFlowApi

  datasource:
    url: jdbc:postgresql://ep-bold-cherry-acx0x5qy-pooler.sa-east-1.aws.neon.tech/StockFlowTESTDB?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_u7cwxOkPUFY3

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update