spring:
  config:
    import: file:.env[.properties]

  application:
    name: StockFlowApi

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400
    issuer: StockFlowApi
